# ISAAC LAB CONFIGURATION - GENERATED BY OPENRGD
# Robot ID: did:rgd:berkeley-humanoid-lite

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg
import isaaclab.sim as sim_utils

class Did:Rgd:BerkeleyHumanoidLiteCfg(ArticulationCfg):
    """Configuration for the robot."""

    spawn = sim_utils.UsdFileCfg(
        usd_path="assets/robot.usd",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
        ),
    )

    init_state = ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.0)
    )

    # --- ACTUATORS ---
    # Grouped by OpenRGD Control Profiles

    CUSTOM_UNNAMED = ImplicitActuatorCfg(
        joint_names_expr=["knee_right_actuator|hip_pitch_right_actuator|ankle_pitch_right_actuator"],
        stiffness=0.0,
        damping=0.0,
        effort_limit=None,  # Loaded from USD
        velocity_limit=None, # Loaded from USD
    )
