name: Build OpenRGD CLI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install base tools and generate requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install toml
          python tools/generate_requirements.py
        shell: cmd

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd

      - name: Run tests (if any)
        run: |
          if exist tests (
            pytest
          ) else (
            echo "No tests/ directory found. Skipping tests."
          )
        shell: cmd

      - name: Build Windows executable with PyInstaller
        run: |
          pyinstaller rgd.spec
        shell: cmd

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openrgd-rgd-windows
          path: dist/rgd.exe

      - name: Publish release asset (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/rgd.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
