# OPENRGD CORE - ALIVE MODULE
# ------------------------------------------------------------------------------
# This module turns source-derived body evidence into a complete OpenRGD profile.
# A packaged seed contributes shared structure and policy, while body-specific
# bindings that are not supported by the imported source are neutralized.
# ------------------------------------------------------------------------------

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
import re
from typing import Any, Dict, Mapping

from .utils import strip_jsonc

SEEDS_ROOT = Path(__file__).resolve().parent.parent / "seeds"
_DID_RE = re.compile(r'(?P<prefix>"id"\s*:\s*")did:rgd:[^"]+(?P<suffix>")')
_BUNDLE_ID_RE = re.compile(
    r'(?P<prefix>"bundle_id_str"\s*:\s*")[^"]+(?P<suffix>")'
)


def _load_seed_spec(seed_name: str) -> Dict[str, str]:
    seed_spec_root = SEEDS_ROOT / seed_name / "spec"
    if not seed_spec_root.exists():
        raise FileNotFoundError(
            f"Seed spec not found for seed '{seed_name}' at: {seed_spec_root}"
        )

    spec_map: Dict[str, str] = {}
    for path in sorted(seed_spec_root.rglob("*")):
        if path.is_file():
            rel_path = path.relative_to(seed_spec_root).as_posix()
            spec_map[rel_path] = path.read_text(encoding="utf-8")
    return spec_map


def _did_component(robot_name: str) -> str:
    normalized = re.sub(r"[^a-z0-9._-]+", "-", robot_name.lower()).strip("._-")
    return normalized or "robot"


def _apply_robot_placeholders(
    content: str,
    *,
    relative_path: str,
    robot_name: str,
    project_id: str,
) -> str:
    rendered = content.replace("{{ROBOT_NAME}}", robot_name)
    rendered = rendered.replace("{{PROJECT_ID}}", project_id)

    did_component = _did_component(robot_name)
    if relative_path == "00_core/kernel.jsonc":
        rendered, count = _DID_RE.subn(
            rf'\g<prefix>did:rgd:{did_component}\g<suffix>',
            rendered,
            count=1,
        )
        if count != 1:
            raise ValueError(
                "seed kernel must contain exactly one OpenRGD DID identity field"
            )
    elif relative_path == "manifest.jsonc":
        rendered, count = _BUNDLE_ID_RE.subn(
            rf'\g<prefix>{did_component}_profile\g<suffix>',
            rendered,
            count=1,
        )
        if count != 1:
            raise ValueError(
                "seed manifest must contain exactly one bundle_id_str field"
            )

    return rendered


def _normalize_partial_path(raw_path: str) -> str:
    normalized = str(raw_path).replace("\\", "/").strip()
    while normalized.startswith("./"):
        normalized = normalized[2:]
    if normalized.startswith("spec/"):
        normalized = normalized[len("spec/") :]

    path = PurePosixPath(normalized)
    if (
        not normalized
        or path.is_absolute()
        or any(part in {"", ".", ".."} for part in path.parts)
        or path.parts[0] == "spec"
    ):
        raise ValueError(f"unsafe partial-spec path: {raw_path!r}")
    return path.as_posix()


def _parse_jsonc_object(text: str, *, path: str) -> dict[str, Any]:
    try:
        value = json.loads(strip_jsonc(text), strict=False)
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSONC while materializing {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"OpenRGD module must contain an object: {path}")
    return value


def _render_generated_jsonc(data: Mapping[str, Any], *, note: str) -> str:
    return (
        "/**\n"
        " * GENERATED BY rgd alive\n"
        f" * {note}\n"
        " */\n\n"
        + json.dumps(data, ensure_ascii=False, allow_nan=False, indent=2)
        + "\n"
    )


def _derive_rigid_body_from_imported_description(description: Mapping[str, Any]) -> dict[str, Any]:
    links: dict[str, Any] = {}
    known_mass = 0.0
    for item in description.get("kinematic_chain_list", []):
        if not isinstance(item, dict):
            continue
        link_id = item.get("link_id_str")
        if not isinstance(link_id, str) or not link_id:
            continue
        inertial = item.get("inertial_properties")
        if not isinstance(inertial, dict):
            inertial = {}
        record: dict[str, Any] = {"data_quality_enum": "SOURCE_DERIVED_PARTIAL"}
        mass = inertial.get("mass_kg_float")
        if isinstance(mass, (int, float)) and not isinstance(mass, bool):
            record["mass_kg_float"] = float(mass)
            known_mass += float(mass)
        com = inertial.get("center_of_mass_xyz_m_vec3_float")
        if isinstance(com, list) and len(com) == 3:
            record["center_of_mass_offset_m_vec3_float"] = com
        tensor = inertial.get("inertia_tensor_xx_yy_zz_xy_xz_yz_kgm2_vec6_float")
        if isinstance(tensor, list) and len(tensor) == 6:
            xx, yy, zz, xy, xz, yz = tensor
            record["inertia_tensor_kg_m2_mat3x3_row_major_arr"] = [
                xx, xy, xz,
                xy, yy, yz,
                xz, yz, zz,
            ]
        links[link_id] = record

    source_meta = description.get("meta_group", {})
    source_artifact = (
        source_meta.get("source_artifact_map", {})
        if isinstance(source_meta, dict)
        else {}
    )
    return {
        "meta_group": {
            "rigid_body_profile_id_str": "imported_body_rigid_dynamics_partial",
            "version_semver_str": "0.2.0",
            "domain_id_str": "01_foundation",
            "file_role_enum": "SOURCE_DERIVED_PARTIAL_RIGID_BODY_PROFILE",
            "profile_completeness_enum": "PARTIAL",
            "source_artifact_map": source_artifact,
        },
        "robot_mass_profile_group": {
            "described_links_mass_kg_float": round(known_mass, 9),
            "data_quality_enum": "SOURCE_DERIVED_PARTIAL",
        },
        "links_rigid_body_map": links,
    }


def _neutralize_unproven_seed_body_bindings(
    full_spec: Dict[str, str],
    normalized_base: Mapping[str, str],
) -> None:
    description_text = normalized_base.get("01_foundation/description.jsonc")
    if description_text is None:
        return
    description = _parse_jsonc_object(
        description_text, path="01_foundation/description.jsonc"
    )
    meta = description.get("meta_group", {})
    if not isinstance(meta, dict) or meta.get("file_role_enum") != "IMPORTED_PARTIAL_DESCRIPTION":
        return

    # The seed can teach structure and policy, but it cannot silently claim that
    # its robot-specific actuator, calibration, firmware or HAL bindings belong
    # to a newly imported body.
    topology_path = "01_foundation/actuation_topology.jsonc"
    if topology_path in full_spec:
        topology = _parse_jsonc_object(full_spec[topology_path], path=topology_path)
        topology.setdefault("meta_group", {})["materialization_status_enum"] = (
            "UNRESOLVED_FOR_IMPORTED_BODY"
        )
        topology["joint_actuator_mapping_map"] = {}
        topology["engineering_design_targets_map"] = {}
        full_spec[topology_path] = _render_generated_jsonc(
            topology,
            note="Seed actuator bindings removed: imported source did not prove them.",
        )

    calibration_path = "01_foundation/calibration.jsonc"
    if calibration_path in full_spec:
        calibration = _parse_jsonc_object(full_spec[calibration_path], path=calibration_path)
        calibration.setdefault("meta_group", {})["materialization_status_enum"] = (
            "NO_IMPORTED_CALIBRATION_EVIDENCE"
        )
        calibration.get("meta_group", {}).pop("target_description_hash_str", None)
        for key in (
            "kinematic_offsets_map",
            "sensor_extrinsics_delta_map",
            "sensor_intrinsics_map",
            "dynamics_correction_map",
            "actuator_calibration_map",
            "planned_calibration_notes_map",
        ):
            if key in calibration:
                calibration[key] = {}
        full_spec[calibration_path] = _render_generated_jsonc(
            calibration,
            note="Seed calibration values removed: calibration is instance evidence.",
        )

    firmware_path = "01_foundation/firmware_mapping.jsonc"
    if firmware_path in full_spec:
        firmware = _parse_jsonc_object(full_spec[firmware_path], path=firmware_path)
        firmware.setdefault("meta_group", {})["materialization_status_enum"] = (
            "NO_IMPORTED_DEVICE_BINDINGS"
        )
        for key in ("device_firmware_map", "planned_device_firmware_map"):
            if key in firmware:
                firmware[key] = {}
        full_spec[firmware_path] = _render_generated_jsonc(
            firmware,
            note="Seed device-to-firmware bindings removed for imported body.",
        )

    hal_path = "01_foundation/hal_mapping.jsonc"
    if hal_path in full_spec:
        hal = _parse_jsonc_object(full_spec[hal_path], path=hal_path)
        hal.setdefault("meta_group", {})["physical_binding_status_enum"] = (
            "UNRESOLVED_FOR_IMPORTED_BODY"
        )
        for key in (
            "actuator_drivers_map",
            "sensor_drivers_map",
            "non_kinematic_actuators_map",
        ):
            if key in hal:
                hal[key] = {}
        full_spec[hal_path] = _render_generated_jsonc(
            hal,
            note="Seed HAL bindings removed: the source file did not authorize hardware mappings.",
        )

    rigid_path = "01_foundation/rigid_body_dynamics.jsonc"
    full_spec[rigid_path] = _render_generated_jsonc(
        _derive_rigid_body_from_imported_description(description),
        note="Rigid-body evidence derived from the imported description where available.",
    )


def alive_rgd_spec(
    base_spec: Mapping[str, str],
    robot_name: str,
    seed_name: str = "default",
) -> Dict[str, str]:
    """Create a complete profile from imported evidence plus a selected seed.

    Imported evidence wins over seed files. Instance-specific seed bindings that
    the source does not prove are neutralized so `rgd alive` can be convenient
    without pretending one reference robot's hardware belongs to another body.
    """

    project_id = f"RGD-{robot_name}"
    normalized_base: Dict[str, str] = {}
    for rel_path, content in base_spec.items():
        if not isinstance(content, str):
            raise ValueError(f"partial-spec content is not text: {rel_path!r}")
        normalized_base[_normalize_partial_path(rel_path)] = content

    seed_spec = _load_seed_spec(seed_name)
    seeded: Dict[str, str] = {}
    for rel_path, content in seed_spec.items():
        seeded[rel_path] = _apply_robot_placeholders(
            content,
            relative_path=rel_path,
            robot_name=robot_name,
            project_id=project_id,
        )

    full_spec: Dict[str, str] = dict(seeded)
    full_spec.update(normalized_base)
    _neutralize_unproven_seed_body_bindings(full_spec, normalized_base)
    return full_spec


def write_manifest(
    rgd_root: Path,
    robot_name: str,
    standard_version: str = "0.1.0",
    *,
    seed_name: str | None = None,
    source_artifact: Mapping[str, Any] | None = None,
) -> Path:
    manifest_path = rgd_root / "manifest.json"
    if manifest_path.exists():
        return manifest_path

    project_id = f"RGD-{robot_name}"
    manifest: dict[str, Any] = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "profile_kind": "SEED_ENRICHED_IMPORTED_EVIDENCE",
        "project_id": project_id,
        "rgd_manifest_version": "0.2.0",
        "robot_name": robot_name,
        "seed_compatibility_status": "UNVERIFIED",
        "body_specific_seed_bindings_status": "NEUTRALIZED_UNLESS_SOURCE_DERIVED",
        "standard_version": standard_version,
    }
    if seed_name is not None:
        manifest["seed_profile"] = seed_name
    if source_artifact is not None:
        manifest["source_artifact"] = dict(source_artifact)

    manifest_path.write_text(
        json.dumps(
            manifest,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return manifest_path


def write_readme(
    rgd_root: Path,
    robot_name: str,
    standard_version: str = "0.1.0",
    *,
    seed_name: str | None = None,
) -> Path:
    readme_path = rgd_root / "README.txt"
    if readme_path.exists():
        return readme_path

    project_id = f"RGD-{robot_name}"
    seed_line = f"Seed profile: {seed_name}\n" if seed_name else ""
    content = (
        f"RGD Profile: {robot_name}\n"
        "---------------------------------------------\n"
        "OpenRGD understood the source description, built a complete profile,\n"
        "validated its structure, generated grounding, compiled the machine\n"
        "bundle and prepared available static interoperability files.\n\n"
        f"Format: OpenRGD v{standard_version}\n"
        f"Project ID: {project_id}\n"
        f"{seed_line}"
        "Body-specific seed bindings: neutralized unless source-derived\n"
        "Seed policy compatibility: review before physical use\n\n"
        "Generated structure:\n"
        "- manifest.json               project provenance\n"
        "- spec/                       integrity-addressed OpenRGD profile\n"
        "- artifacts/grounding_context.json\n"
        "- spec/openrgd_unified_spec.json\n"
        "- export/ros2/                static ROS 2 interoperability\n\n"
        "Your robot is alive in OpenRGD. Explore the profile, improve it, and\n"
        "bind real hardware only through reviewed runtime/body-adapter evidence.\n"
    )
    readme_path.write_text(content, encoding="utf-8", newline="\n")
    return readme_path
