#!/usr/bin/env python3
"""
Utility script to generate requirements.txt from pyproject.toml.

Source of truth:
    - pyproject.toml [project.dependencies]

Output:
    - requirements.txt (auto-generated, NOT meant for manual editing)

This keeps the project configuration centralized while still supporting
classic pip workflows and CI environments that expect requirements.txt.
"""

import sys
from pathlib import Path

import toml


def main() -> int:
    root = Path(".").resolve()
    pyproject = root / "pyproject.toml"

    if not pyproject.exists():
        print("[ERROR] pyproject.toml not found at repository root.")
        return 1

    try:
        data = toml.load(pyproject)
    except Exception as e:
        print(f"[ERROR] Failed to parse pyproject.toml: {e}")
        return 1

    project = data.get("project", {})
    deps = project.get("dependencies", [])

    if not isinstance(deps, list):
        print("[ERROR] project.dependencies in pyproject.toml is not a list.")
        return 1

    req_path = root / "requirements.txt"

    header_lines = [
        "# Do not edit this file manually.",
        "# It is auto-generated from pyproject.toml via tools/generate_requirements.py",
        "# Source of truth: [project.dependencies] in pyproject.toml",
        "",
    ]

    content_lines = header_lines + deps
    req_path.write_text("\n".join(content_lines) + "\n", encoding="utf-8")

    print(f"[OK] requirements.txt generated with {len(deps)} dependencies.")
    print(f"[INFO] Path: {req_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
